rac: run cargo in offline mode
As suggested by the build error message:

   error: the lock file .../rac/0.0+git/git/Cargo.lock needs to be
   updated but --frozen was passed to prevent this.
   If you want to try to generate the lock file without accessing
   the network, remove the --frozen flag and use --offline instead.

set CARGO_BUILD_FLAGS accordingly to prevent that error.

Signed-off-by: Rogerio Guerra Borin <rogerio.borin@toradex.com>
(cherry picked from commit 0f164203899946b6f26d5cd8f96a63bbd996494a)
Signed-off-by: Eduardo Ferreira <eduardo.barbosa@toradex.com>