recipes: fix S, WORDIR and UNPACKDIR assignements
Now bitbake can assign some S values automatically and now UNPACKDIR
should be used instead of WORKDIR. These changes will fix errors like
the following:

ERROR: aktualizr-reboot-1.0-r0 do_unpack: S should be set relative to
UNPACKDIR, e.g. replace WORKDIR with UNPACKDIR in "S =
${WORKDIR}/sources"

Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>