meta-virtualization:linux: add fix for kmeta paths
When I build my image of Torizon OS, I face the following error:
| DEBUG: Using /home/ed/torizon-integration-walnascar/layers/meta-virtualization/recipes-kernel/linux/linux-yocto/extra-configs.cfg for extra-configs.cfg
| DEBUG: Executing shell function do_kernel_metadata
| NOTE: do_kernel_metadata: for summary/debug, set KCONF_AUDIT_LEVEL > 0
| ERROR: could not find file cfg/lxc.scc, included from /home/ed/torizon-integration-walnascar/verdin-imx95-build/tmp/work/verdin_imx95-tdx-linux/linux-toradex-imx/6.12.49+git/recipe-sysroot-native/kcfg/cfg/docker.scc
| ERROR: could not process input files: /home/ed/torizon-integration-walnascar/layers/meta-toradex-nxp/recipes-kernel/linux/linux-toradex-imx/nxp-imx.cfg /home/ed/torizon-integration-walnascar/layers/meta-virtualization/recipes-kernel/linux/linux-yocto/extra-configs.cfg bsp/verdin-imx95-standard-torizon.scc ../../recipe-sysroot-native/kcfg/cfg/virtio.scc ../../recipe-sysroot-native/kcfg/cfg/xt-checksum.scc ../../recipe-sysroot-native/kcfg/cfg/vswitch.scc ../../recipe-sysroot-native/kcfg/cfg/lxc.scc ../../recipe-sysroo→
|        See /tmp/tmp.tDpnmc4f03 for details
| ERROR: Could not generate configuration queue for verdin-imx95.
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/ed/torizon-integration-walnascar/layers/meta-toradex-nxp/recipes-kernel/linux/linux-toradex-imx_6.12-2.0.x.bb:do_kernel_metadata) failed with exit code '1'
NOTE: Tasks Summary: Attempted 9437 tasks of which 8399 didn't need to be rerun and 1 failed.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 5 seconds

Summary: 1 task failed:
  /home/ed/torizon-integration-walnascar/layers/meta-toradex-nxp/recipes-kernel/linux/linux-toradex-imx_6.12-2.0.x.bb:do_kernel_metadata
    log: /home/ed/torizon-integration-walnascar/verdin-imx95-build/tmp/work/verdin_imx95-tdx-linux/linux-toradex-imx/6.12.49+git/temp/log.do_kernel_metadata.230922
Summary: There were 2 WARNING messages.
Summary: There were 2 ERROR messages, returning a non-zero exit code.

This issue revolves around meta-virtualization detecting some kernel
features and enabling some .scc's from Yocto kmeta. But due to how
they're adding the kmeta, and the relative path they're appending to
each config, causes this build issue.

If we check the error message, the .scc file inside
'recipe-sysroot-native/kcfg/' is found, but the include in it isn't.
Digging I found that these are the paths searched by
'do_kernel_metadata':
 ${UNPACKDIR}/$f/kernel-meta  |- Check SRC_URI for "kmeta" type'd git repositories and directories.
 ${UNPACKDIR}/$f              |   Return the name of the repository or directory as it will be found in UNPACKDIR. This will be stored in '$f'
 ${sdir}              |- scc's and patches included in SRC_URI
 ${sdir}/kernel-meta  |
 ${S}/arch/${ARCH}/configs
 ${S}/kernel/configs

And these double as the paths searched by the tool on the .scc's include
directives.
Notice that there's no path there to where the kmeta is being installed
by 'yocto-cfg-fragments-%' recipe.

So, in order to fix the issue we can add a prepend on the
'do_kernel_metadata' task, and add
'-I${WORKDIR}/recipe-sysroot-native/kcfg' path to it, which is where it
is being installed.

Related-to: TOR-4190
Signed-off-by: Eduardo Ferreira <eduardo.barbosa@toradex.com>