setup-environment-intel: add meta-toradex-security and dependencies
These layers are required for implementing secure-boot features on x86.
Note that meta-tpm is provided by meta-security and must be included
to fix the parsing error:

```
ERROR: No recipes in default available for:
  layers/meta-toradex-security/recipes-tpm2/tpm2-tools/tpm2-tools_%.bbappend
```

Signed-off-by: Tanguy Raufflet <tanguy.raufflet@savoirfairelinux.com>