Revert "Add bootloader deploy to OTA_FILES_DEPENDS."
Commit d9a020c[1] introduced an issue on Common Torizon builds for x86:
  ERROR: Nothing PROVIDES 'virtual/bootloader'
  u-boot PROVIDES virtual/bootloader but was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the intel-corei7-64 machine configuration.
  ERROR: Required build target 'torizon-docker' has no buildable providers.
  Missing or unbuildable dependency chain was: ['torizon-docker', 'virtual/bootloader']

  Summary: There were 2 ERROR messages, returning a non-zero exit code.

[1] https://github.com/torizon/meta-toradex-torizon/pull/417/commits/d9a020c9eaea00be364678dda4c159656e629e33

This reverts commit d9a020c9eaea00be364678dda4c159656e629e33.

Signed-off-by: Eduardo Ferreira <eduardo.barbosa@toradex.com>